export const ADD_PROFILE ='ADD_PROFILE'
export const REMOVE_PROFILE  ='REMOVE_PROFILE'
export const EDIT_PROFILES  ='EDIT_PROFILES'

export const OPEN_ALERT  ='OPEN_ALERT'

export const CLOSE_ALERT ='CLOSE_ALERT'

export const ENABLE_EDIT_MODE ='ENABLE_EDIT_MODE'
export const DISABLE_EDIT_MODE ='DISABLE_EDIT_MODE'

export const VALIDATE_PROFILE ='VALIDATE_PROFILE'

export const MOVE_UP_PROFILE ='MOVE_UP_PROFILE'
export const MOVE_DOWN_PROFILE ='MOVE_DOWN_PROFILE'

export const SET_CURRENT_PROFILE ='SET_CURRENT_PROFILE'



export const FETCH_PROFILES  ='FETCH_PROFILES'
